stages:
  - build
  - deploy

backend:
  stage: build
  tags:
    - tastamat
  script:
    - ./gradlew tastamat-api:shadowJar

tastamat-api-deploy-test:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  tags:
    - tastamat
  before_script:
    - cp tastamat-api/build/libs/tastamat-api-fat.jar /var/toolpar/tastamat/
  script:
    - |
      cd /var/toolpar/tastamat
      java -jar tastamat-api-fat.jar stop tastamat-api-fat.jar
  after_script:
    - |
      cd /var/toolpar/tastamat
      java -jar tastamat-api-fat.jar start -conf=conf/app.json
  when: manual
  only:
    - dev
  allow_failure:
    exit_codes: 1
