version: '2.1'
services:
  web:
    image: nginx
    ports:
      - "80:80"
    links:
      - tastamat-backend
    volumes:
      - "./tastamat-web-server/nginx.conf:/etc/nginx/nginx.conf"
  tastamat-backend:
    image: registry.gitlab.com/toolpar/tastamat/tastamat-api:dev
    command: "run kz.zx.api.app.AppVerticle --launcher-class=kz.toolpar.bootstrap.AppLauncher --conf=/opt/conf/app.json"
    volumes:
      - "./tastamat-api/conf:/opt/conf"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  db:
    image: registry.gitlab.com/toolpar/tastamat/tastamat-db:dev
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - "./volumes/db:/var/lib/postgresql/data:z"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
