package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2019-01-05T23:45:47.507+06:00
 * Generated source version: 2.7.14.redhat-1
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "SendSMSService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SendSMSService {

    @WebMethod(operationName = "GetInfoByID", action = "urn:SendSMSLib-SendSMSService#GetInfoByID")
    @WebResult(name = "SendSMSService___GetInfoByIDResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public SendSMSServiceGetInfoByIDResponse getInfoByID(
        @WebParam(partName = "parameters", name = "SendSMSService___GetInfoByID", targetNamespace = "http://tempuri.org/")
        SendSMSServiceGetInfoByID parameters
    );

    @WebMethod(operationName = "SendBulkMessage", action = "urn:SendSMSLib-SendSMSService#SendBulkMessage")
    @WebResult(name = "SendSMSService___SendBulkMessageResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public SendSMSServiceSendBulkMessageResponse sendBulkMessage(
        @WebParam(partName = "parameters", name = "SendSMSService___SendBulkMessage", targetNamespace = "http://tempuri.org/")
        SendSMSServiceSendBulkMessage parameters
    );

    @WebMethod(operationName = "GetBulkInfoByID", action = "urn:SendSMSLib-SendSMSService#GetBulkInfoByID")
    @WebResult(name = "SendSMSService___GetBulkInfoByIDResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public SendSMSServiceGetBulkInfoByIDResponse getBulkInfoByID(
        @WebParam(partName = "parameters", name = "SendSMSService___GetBulkInfoByID", targetNamespace = "http://tempuri.org/")
        SendSMSServiceGetBulkInfoByID parameters
    );

    @WebMethod(operationName = "GetInboxMessage", action = "urn:SendSMSLib-SendSMSService#GetInboxMessage")
    @WebResult(name = "SendSMSService___GetInboxMessageResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public SendSMSServiceGetInboxMessageResponse getInboxMessage(
        @WebParam(partName = "parameters", name = "SendSMSService___GetInboxMessage", targetNamespace = "http://tempuri.org/")
        SendSMSServiceGetInboxMessage parameters
    );

    @WebMethod(operationName = "SendMessageTlv", action = "urn:SendSMSLib-SendSMSService#SendMessageTlv")
    @WebResult(name = "SendSMSService___SendMessageResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public SendSMSServiceSendMessageResponse sendMessageTlv(
        @WebParam(partName = "parameters", name = "SendSMSService___SendMessageTlv", targetNamespace = "http://tempuri.org/")
        SendSMSServiceSendMessageTlv parameters
    );

    @WebMethod(operationName = "SendMessage", action = "urn:SendSMSLib-SendSMSService#SendMessage")
    @WebResult(name = "SendSMSService___SendMessageResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public SendSMSServiceSendMessageResponse sendMessage(
        @WebParam(partName = "parameters", name = "SendSMSService___SendMessage", targetNamespace = "http://tempuri.org/")
        SendSMSServiceSendMessage parameters
    );

    @WebMethod(operationName = "GetReport", action = "urn:SendSMSLib-SendSMSService#GetReport")
    @WebResult(name = "SendSMSService___GetReportResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public SendSMSServiceGetReportResponse getReport(
        @WebParam(partName = "parameters", name = "SendSMSService___GetReport", targetNamespace = "http://tempuri.org/")
        SendSMSServiceGetReport parameters
    );

    @WebMethod(operationName = "GetAbonents", action = "urn:SendSMSLib-SendSMSService#GetAbonents")
    @WebResult(name = "SendSMSService___GetAbonentsResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public SendSMSServiceGetAbonentsResponse getAbonents(
        @WebParam(partName = "parameters", name = "SendSMSService___GetAbonents", targetNamespace = "http://tempuri.org/")
        SendSMSServiceGetAbonents parameters
    );
}
