package kz.zx.api.enums;

/**
 * Created by deedarb on 7/14/17.
 */
public enum ConfigKey {
	JMS, STORE_PREFIX, CONFIG_FOLDER, CONFIG_PATH, PATH, ONLYOFFICE,
	WEB, PORT, HOST, DATASOURCE, USERNAME, PASSWORD, JDBC_URL, DATASOURCES,
	MAX_POOL_SIZE, VERTICLES, ENABLED, VERTICLE_CLASS,
	INSTANCE_COUNT, POOL_SIZE, SECURE, SERVICES, SERVICE_BUS_URL, WS, FILESTORAGE, CONFIGURATOR,
	URL, CONSUMER_COUNT, MAX_CONSUMER_COUNT, PREFETCH, REDELIVERY_DELAY, REDELIVERY_COUNT, QUEUES, NAME, WORKER,SOAP, KEY,
	SCHEDULER, BEGIN, INTERVAL, KEYCLOAK, ADMIN, USER, CLIENT_ID, REALM, CLIENT_SECRET, APP_URL, VK, ACCESS_TOKEN, PREFIX;

	public String key() {
		return this.name().toLowerCase();
	}
}
