/*
 * This file is generated by jOOQ.
*/
package kz.tastamat.db.model.jooq;


import javax.annotation.Generated;

import kz.tastamat.db.model.jooq.tables.JqOrder;
import kz.tastamat.db.model.jooq.tables.JqPayment;
import kz.tastamat.db.model.jooq.tables.JqProfile;
import kz.tastamat.db.model.jooq.tables.JqUser;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ORDER_PKEY = Indexes0.ORDER_PKEY;
    public static final Index PAYMENT_PKEY = Indexes0.PAYMENT_PKEY;
    public static final Index PROFILE_PKEY = Indexes0.PROFILE_PKEY;
    public static final Index USER_PKEY = Indexes0.USER_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index ORDER_PKEY = createIndex("tt_order_pkey", JqOrder.ORDER, new OrderField[] { JqOrder.ORDER.ID }, true);
        public static Index PAYMENT_PKEY = createIndex("tt_payment_pkey", JqPayment.PAYMENT, new OrderField[] { JqPayment.PAYMENT.ID }, true);
        public static Index PROFILE_PKEY = createIndex("wx_profile_pkey", JqProfile.PROFILE, new OrderField[] { JqProfile.PROFILE.ID }, true);
        public static Index USER_PKEY = createIndex("wx_user_pkey", JqUser.USER, new OrderField[] { JqUser.USER.ID }, true);
    }
}
