/*
 * This file is generated by jOOQ.
*/
package kz.tastamat.db.model.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import kz.tastamat.db.model.jooq.tables.JqOrder;
import kz.tastamat.db.model.jooq.tables.JqPayment;
import kz.tastamat.db.model.jooq.tables.JqProfile;
import kz.tastamat.db.model.jooq.tables.JqUser;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JqPublic extends SchemaImpl {

    private static final long serialVersionUID = 780162726;

    /**
     * The reference instance of <code>public</code>
     */
    public static final JqPublic PUBLIC = new JqPublic();

    /**
     * The table <code>public.tt_order</code>.
     */
    public final JqOrder ORDER = kz.tastamat.db.model.jooq.tables.JqOrder.ORDER;

    /**
     * The table <code>public.tt_payment</code>.
     */
    public final JqPayment PAYMENT = kz.tastamat.db.model.jooq.tables.JqPayment.PAYMENT;

    /**
     * The table <code>public.wx_profile</code>.
     */
    public final JqProfile PROFILE = kz.tastamat.db.model.jooq.tables.JqProfile.PROFILE;

    /**
     * The table <code>public.wx_user</code>.
     */
    public final JqUser USER = kz.tastamat.db.model.jooq.tables.JqUser.USER;

    /**
     * No further instances allowed
     */
    private JqPublic() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.FILE_SEQUENCE,
            Sequences.ORDER_SEQUENCE,
            Sequences.ORGANIZATION_SEQUENCE,
            Sequences.PAYMENT_SEQUENCE,
            Sequences.PROFILE_SEQUENCE,
            Sequences.REQUEST_SEQUENCE,
            Sequences.USER_SEQUENCE);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            JqOrder.ORDER,
            JqPayment.PAYMENT,
            JqProfile.PROFILE,
            JqUser.USER);
    }
}
