/*
 * This file is generated by jOOQ.
*/
package kz.tastamat.db.model.jooq;


import javax.annotation.Generated;

import kz.tastamat.db.model.jooq.routines.JqGenericStamp;

import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public static Object genericStamp(Configuration configuration) {
        JqGenericStamp f = new JqGenericStamp();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public static Field<Object> genericStamp() {
        JqGenericStamp f = new JqGenericStamp();

        return f.asField();
    }
}
