/*
 * This file is generated by jOOQ.
*/
package kz.tastamat.db.model.jooq;


import javax.annotation.Generated;

import kz.tastamat.db.model.jooq.tables.JqOrder;
import kz.tastamat.db.model.jooq.tables.JqPayment;
import kz.tastamat.db.model.jooq.tables.JqProfile;
import kz.tastamat.db.model.jooq.tables.JqUser;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.tt_order</code>.
     */
    public static final JqOrder ORDER = kz.tastamat.db.model.jooq.tables.JqOrder.ORDER;

    /**
     * The table <code>public.tt_payment</code>.
     */
    public static final JqPayment PAYMENT = kz.tastamat.db.model.jooq.tables.JqPayment.PAYMENT;

    /**
     * The table <code>public.wx_profile</code>.
     */
    public static final JqProfile PROFILE = kz.tastamat.db.model.jooq.tables.JqProfile.PROFILE;

    /**
     * The table <code>public.wx_user</code>.
     */
    public static final JqUser USER = kz.tastamat.db.model.jooq.tables.JqUser.USER;
}
