/*
 * This file is generated by jOOQ.
*/
package kz.tastamat.db.model.jooq.tables.records;


import java.time.OffsetDateTime;

import javax.annotation.Generated;

import kz.tastamat.db.model.jooq.tables.JqOrder;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JqOrderRecord extends UpdatableRecordImpl<JqOrderRecord> implements Record16<Long, OffsetDateTime, OffsetDateTime, Long, String, String, String, Long, String, String, String, OffsetDateTime, String, OffsetDateTime, String, Boolean> {

    private static final long serialVersionUID = -1304206341;

    /**
     * Setter for <code>public.tt_order.id_</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tt_order.id_</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tt_order.create_date_</code>.
     */
    public void setCreateDate(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tt_order.create_date_</code>.
     */
    public OffsetDateTime getCreateDate() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for <code>public.tt_order.modify_date_</code>.
     */
    public void setModifyDate(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tt_order.modify_date_</code>.
     */
    public OffsetDateTime getModifyDate() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.tt_order.creator_</code>.
     */
    public void setCreator(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tt_order.creator_</code>.
     */
    public Long getCreator() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.tt_order.identificator_</code>.
     */
    public void setIdentificator(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tt_order.identificator_</code>.
     */
    public String getIdentificator() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tt_order.recipient_name_</code>.
     */
    public void setRecipientName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tt_order.recipient_name_</code>.
     */
    public String getRecipientName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.tt_order.recipient_phone_</code>.
     */
    public void setRecipientPhone(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tt_order.recipient_phone_</code>.
     */
    public String getRecipientPhone() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.tt_order.locker_id_</code>.
     */
    public void setLockerId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.tt_order.locker_id_</code>.
     */
    public Long getLockerId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.tt_order.locker_code_</code>.
     */
    public void setLockerCode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.tt_order.locker_code_</code>.
     */
    public String getLockerCode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.tt_order.box_size_</code>.
     */
    public void setBoxSize(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.tt_order.box_size_</code>.
     */
    public String getBoxSize() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.tt_order.drop_code_</code>.
     */
    public void setDropCode(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.tt_order.drop_code_</code>.
     */
    public String getDropCode() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.tt_order.drop_date_</code>.
     */
    public void setDropDate(OffsetDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.tt_order.drop_date_</code>.
     */
    public OffsetDateTime getDropDate() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for <code>public.tt_order.pick_code_</code>.
     */
    public void setPickCode(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.tt_order.pick_code_</code>.
     */
    public String getPickCode() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.tt_order.pick_date_</code>.
     */
    public void setPickDate(OffsetDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.tt_order.pick_date_</code>.
     */
    public OffsetDateTime getPickDate() {
        return (OffsetDateTime) get(13);
    }

    /**
     * Setter for <code>public.tt_order.status_</code>.
     */
    public void setStatus(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.tt_order.status_</code>.
     */
    public String getStatus() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.tt_order.sms_</code>.
     */
    public void setSms(Boolean value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.tt_order.sms_</code>.
     */
    public Boolean getSms() {
        return (Boolean) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, OffsetDateTime, OffsetDateTime, Long, String, String, String, Long, String, String, String, OffsetDateTime, String, OffsetDateTime, String, Boolean> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, OffsetDateTime, OffsetDateTime, Long, String, String, String, Long, String, String, String, OffsetDateTime, String, OffsetDateTime, String, Boolean> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return JqOrder.ORDER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field2() {
        return JqOrder.ORDER.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field3() {
        return JqOrder.ORDER.MODIFY_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return JqOrder.ORDER.CREATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return JqOrder.ORDER.IDENTIFICATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return JqOrder.ORDER.RECIPIENT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return JqOrder.ORDER.RECIPIENT_PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return JqOrder.ORDER.LOCKER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return JqOrder.ORDER.LOCKER_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return JqOrder.ORDER.BOX_SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return JqOrder.ORDER.DROP_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field12() {
        return JqOrder.ORDER.DROP_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return JqOrder.ORDER.PICK_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field14() {
        return JqOrder.ORDER.PICK_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return JqOrder.ORDER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field16() {
        return JqOrder.ORDER.SMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component2() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component3() {
        return getModifyDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getCreator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getIdentificator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getRecipientName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getRecipientPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getLockerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getLockerCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getBoxSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getDropCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component12() {
        return getDropDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getPickCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component14() {
        return getPickDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component16() {
        return getSms();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value2() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value3() {
        return getModifyDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getCreator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getIdentificator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getRecipientName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getRecipientPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getLockerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getLockerCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getBoxSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getDropCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value12() {
        return getDropDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getPickCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value14() {
        return getPickDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value16() {
        return getSms();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqOrderRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqOrderRecord value2(OffsetDateTime value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqOrderRecord value3(OffsetDateTime value) {
        setModifyDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqOrderRecord value4(Long value) {
        setCreator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqOrderRecord value5(String value) {
        setIdentificator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqOrderRecord value6(String value) {
        setRecipientName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqOrderRecord value7(String value) {
        setRecipientPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqOrderRecord value8(Long value) {
        setLockerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqOrderRecord value9(String value) {
        setLockerCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqOrderRecord value10(String value) {
        setBoxSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqOrderRecord value11(String value) {
        setDropCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqOrderRecord value12(OffsetDateTime value) {
        setDropDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqOrderRecord value13(String value) {
        setPickCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqOrderRecord value14(OffsetDateTime value) {
        setPickDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqOrderRecord value15(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqOrderRecord value16(Boolean value) {
        setSms(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqOrderRecord values(Long value1, OffsetDateTime value2, OffsetDateTime value3, Long value4, String value5, String value6, String value7, Long value8, String value9, String value10, String value11, OffsetDateTime value12, String value13, OffsetDateTime value14, String value15, Boolean value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JqOrderRecord
     */
    public JqOrderRecord() {
        super(JqOrder.ORDER);
    }

    /**
     * Create a detached, initialised JqOrderRecord
     */
    public JqOrderRecord(Long id_, OffsetDateTime createDate_, OffsetDateTime modifyDate_, Long creator_, String identificator_, String recipientName_, String recipientPhone_, Long lockerId_, String lockerCode_, String boxSize_, String dropCode_, OffsetDateTime dropDate_, String pickCode_, OffsetDateTime pickDate_, String status_, Boolean sms_) {
        super(JqOrder.ORDER);

        set(0, id_);
        set(1, createDate_);
        set(2, modifyDate_);
        set(3, creator_);
        set(4, identificator_);
        set(5, recipientName_);
        set(6, recipientPhone_);
        set(7, lockerId_);
        set(8, lockerCode_);
        set(9, boxSize_);
        set(10, dropCode_);
        set(11, dropDate_);
        set(12, pickCode_);
        set(13, pickDate_);
        set(14, status_);
        set(15, sms_);
    }
}
