/*
 * This file is generated by jOOQ.
*/
package kz.tastamat.db.model.jooq.tables.records;


import java.time.OffsetDateTime;

import javax.annotation.Generated;

import kz.tastamat.db.model.jooq.tables.JqProfile;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JqProfileRecord extends UpdatableRecordImpl<JqProfileRecord> implements Record12<Long, OffsetDateTime, OffsetDateTime, Long, String, String, OffsetDateTime, String, String, OffsetDateTime, Long, String> {

    private static final long serialVersionUID = -675911031;

    /**
     * Setter for <code>public.wx_profile.id_</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.wx_profile.id_</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.wx_profile.create_date_</code>.
     */
    public void setCreateDate(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.wx_profile.create_date_</code>.
     */
    public OffsetDateTime getCreateDate() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for <code>public.wx_profile.modify_date_</code>.
     */
    public void setModifyDate(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.wx_profile.modify_date_</code>.
     */
    public OffsetDateTime getModifyDate() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.wx_profile.user_</code>.
     */
    public void setUser(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.wx_profile.user_</code>.
     */
    public Long getUser() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.wx_profile.firstname_</code>.
     */
    public void setFirstname(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.wx_profile.firstname_</code>.
     */
    public String getFirstname() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.wx_profile.lastname_</code>.
     */
    public void setLastname(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.wx_profile.lastname_</code>.
     */
    public String getLastname() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.wx_profile.birth_date_</code>.
     */
    public void setBirthDate(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.wx_profile.birth_date_</code>.
     */
    public OffsetDateTime getBirthDate() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.wx_profile.doc_type_</code>.
     */
    public void setDocType(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.wx_profile.doc_type_</code>.
     */
    public String getDocType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.wx_profile.doc_number_</code>.
     */
    public void setDocNumber(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.wx_profile.doc_number_</code>.
     */
    public String getDocNumber() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.wx_profile.doc_exp_date_</code>.
     */
    public void setDocExpDate(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.wx_profile.doc_exp_date_</code>.
     */
    public OffsetDateTime getDocExpDate() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>public.wx_profile.wallet_</code>.
     */
    public void setWallet(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.wx_profile.wallet_</code>.
     */
    public Long getWallet() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.wx_profile.template_</code>.
     */
    public void setTemplate(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.wx_profile.template_</code>.
     */
    public String getTemplate() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, OffsetDateTime, OffsetDateTime, Long, String, String, OffsetDateTime, String, String, OffsetDateTime, Long, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, OffsetDateTime, OffsetDateTime, Long, String, String, OffsetDateTime, String, String, OffsetDateTime, Long, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return JqProfile.PROFILE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field2() {
        return JqProfile.PROFILE.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field3() {
        return JqProfile.PROFILE.MODIFY_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return JqProfile.PROFILE.USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return JqProfile.PROFILE.FIRSTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return JqProfile.PROFILE.LASTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field7() {
        return JqProfile.PROFILE.BIRTH_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return JqProfile.PROFILE.DOC_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return JqProfile.PROFILE.DOC_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field10() {
        return JqProfile.PROFILE.DOC_EXP_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return JqProfile.PROFILE.WALLET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return JqProfile.PROFILE.TEMPLATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component2() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component3() {
        return getModifyDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getLastname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component7() {
        return getBirthDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getDocType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getDocNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component10() {
        return getDocExpDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component11() {
        return getWallet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getTemplate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value2() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value3() {
        return getModifyDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLastname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value7() {
        return getBirthDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getDocType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getDocNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value10() {
        return getDocExpDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getWallet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getTemplate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqProfileRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqProfileRecord value2(OffsetDateTime value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqProfileRecord value3(OffsetDateTime value) {
        setModifyDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqProfileRecord value4(Long value) {
        setUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqProfileRecord value5(String value) {
        setFirstname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqProfileRecord value6(String value) {
        setLastname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqProfileRecord value7(OffsetDateTime value) {
        setBirthDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqProfileRecord value8(String value) {
        setDocType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqProfileRecord value9(String value) {
        setDocNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqProfileRecord value10(OffsetDateTime value) {
        setDocExpDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqProfileRecord value11(Long value) {
        setWallet(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqProfileRecord value12(String value) {
        setTemplate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqProfileRecord values(Long value1, OffsetDateTime value2, OffsetDateTime value3, Long value4, String value5, String value6, OffsetDateTime value7, String value8, String value9, OffsetDateTime value10, Long value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JqProfileRecord
     */
    public JqProfileRecord() {
        super(JqProfile.PROFILE);
    }

    /**
     * Create a detached, initialised JqProfileRecord
     */
    public JqProfileRecord(Long id_, OffsetDateTime createDate_, OffsetDateTime modifyDate_, Long user_, String firstname_, String lastname_, OffsetDateTime birthDate_, String docType_, String docNumber_, OffsetDateTime docExpDate_, Long wallet_, String template_) {
        super(JqProfile.PROFILE);

        set(0, id_);
        set(1, createDate_);
        set(2, modifyDate_);
        set(3, user_);
        set(4, firstname_);
        set(5, lastname_);
        set(6, birthDate_);
        set(7, docType_);
        set(8, docNumber_);
        set(9, docExpDate_);
        set(10, wallet_);
        set(11, template_);
    }
}
