/*
 * This file is generated by jOOQ.
*/
package kz.tastamat.db.model.jooq.tables.records;


import java.time.OffsetDateTime;

import javax.annotation.Generated;

import kz.tastamat.db.model.jooq.tables.JqUser;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JqUserRecord extends UpdatableRecordImpl<JqUserRecord> implements Record9<Long, OffsetDateTime, OffsetDateTime, String, String, String, String, Boolean, Boolean> {

    private static final long serialVersionUID = -1911436872;

    /**
     * Setter for <code>public.wx_user.id_</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.wx_user.id_</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.wx_user.create_date_</code>.
     */
    public void setCreateDate(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.wx_user.create_date_</code>.
     */
    public OffsetDateTime getCreateDate() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for <code>public.wx_user.modify_date_</code>.
     */
    public void setModifyDate(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.wx_user.modify_date_</code>.
     */
    public OffsetDateTime getModifyDate() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.wx_user.phone_</code>.
     */
    public void setPhone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.wx_user.phone_</code>.
     */
    public String getPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.wx_user.sms_code_</code>.
     */
    public void setSmsCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.wx_user.sms_code_</code>.
     */
    public String getSmsCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.wx_user.password_</code>.
     */
    public void setPassword(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.wx_user.password_</code>.
     */
    public String getPassword() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.wx_user.role_</code>.
     */
    public void setRole(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.wx_user.role_</code>.
     */
    public String getRole() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.wx_user.confirmed_</code>.
     */
    public void setConfirmed(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.wx_user.confirmed_</code>.
     */
    public Boolean getConfirmed() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.wx_user.enabled_</code>.
     */
    public void setEnabled(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.wx_user.enabled_</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, OffsetDateTime, OffsetDateTime, String, String, String, String, Boolean, Boolean> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, OffsetDateTime, OffsetDateTime, String, String, String, String, Boolean, Boolean> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return JqUser.USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field2() {
        return JqUser.USER.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field3() {
        return JqUser.USER.MODIFY_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return JqUser.USER.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return JqUser.USER.SMS_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return JqUser.USER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return JqUser.USER.ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return JqUser.USER.CONFIRMED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return JqUser.USER.ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component2() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component3() {
        return getModifyDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getSmsCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component8() {
        return getConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component9() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value2() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value3() {
        return getModifyDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSmsCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqUserRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqUserRecord value2(OffsetDateTime value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqUserRecord value3(OffsetDateTime value) {
        setModifyDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqUserRecord value4(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqUserRecord value5(String value) {
        setSmsCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqUserRecord value6(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqUserRecord value7(String value) {
        setRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqUserRecord value8(Boolean value) {
        setConfirmed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqUserRecord value9(Boolean value) {
        setEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JqUserRecord values(Long value1, OffsetDateTime value2, OffsetDateTime value3, String value4, String value5, String value6, String value7, Boolean value8, Boolean value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JqUserRecord
     */
    public JqUserRecord() {
        super(JqUser.USER);
    }

    /**
     * Create a detached, initialised JqUserRecord
     */
    public JqUserRecord(Long id_, OffsetDateTime createDate_, OffsetDateTime modifyDate_, String phone_, String smsCode_, String password_, String role_, Boolean confirmed_, Boolean enabled_) {
        super(JqUser.USER);

        set(0, id_);
        set(1, createDate_);
        set(2, modifyDate_);
        set(3, phone_);
        set(4, smsCode_);
        set(5, password_);
        set(6, role_);
        set(7, confirmed_);
        set(8, enabled_);
    }
}
